name: Update flake inputs

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Update flake inputs
        run: nix flake update

      - name: Format
        run: nix run nixpkgs#alejandra -- -q .

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-flake
          commit-message: "chore: update flake inputs"
          title: "chore: update flake inputs"
          body: |
            Automated weekly update of flake inputs.
          labels: chore, dependencies
          signoff: false
